feat: enable `one-job` to request a particular job (#1443)
Extend `forgejo-runner one-job` with the ability to ask Forgejo for a particular job attempt for execution by passing the option `--handle <handle>`. `forgejo-runner one-job --handle 9d52c7d8-aebe-426b-b015-dd453aacaada` will ask Forgejo for the attempt with the handle `9d52c7d8-aebe-426b-b015-dd453aacaada`. If the job attempt is not ready, not suitable for the runner, or unknown, Forgejo will not return a task.

The feature requires collaboration from Forgejo. As it uses a new RPC, it only works with Forgejo 15.

See https://code.forgejo.org/forgejo/forgejo-actions-feature-requests/issues/76 for the motivation and design considerations.

Example usage:

```
$ curl -u andreas --basic http://192.168.178.62:3000/api/v1/repos/andreas/test/actions/runners/jobs
[{"id":301,"attempt":1,"handle":"9d52c7d8-aebe-426b-b015-dd453aacaada","repo_id":1,"owner_id":1,"name":"test","needs":null,"runs_on":["debian"],"task_id":0,"status":"waiting"},{"id":300,"attempt":1,"handle":"","repo_id":1,"owner_id":1,"name":"test","needs":null,"runs_on":["debian"],"task_id":0,"status":"waiting"}]
$ forgejo-runner one-job --handle invalid
INFO[0000] No configuration file specified; using default settings.
INFO[2026-03-24T17:05:34+01:00] Starting job
INFO[2026-03-24T17:05:34+01:00] runner: forgejo-debug, with version: v12.7.2+10-ga53c8ada, with labels: [debian docker], ephemeral: false, declared successfully
Error: could not fetch task
$ forgejo-runner one-job --handle 9d52c7d8-aebe-426b-b015-dd453aacaada
INFO[0000] No configuration file specified; using default settings.
INFO[2026-03-24T17:04:59+01:00] Starting job
INFO[2026-03-24T17:04:59+01:00] runner: forgejo-debug, with version: v12.7.2+10-ga53c8ada, with labels: [debian docker], ephemeral: false, declared successfully
INFO[2026-03-24T17:04:59+01:00] task 214 repo is andreas/test https://data.forgejo.org http://192.168.178.62:3000/
INFO[2026-03-24T17:05:04+01:00] Cleaning up network for job test, and network name is: WORKFLOW-73f75b8948e73b075df5ca63264c6025
$ curl -u andreas --basic http://192.168.178.62:3000/api/v1/repos/andreas/test/actions/runners/jobs
[{"id":300,"attempt":1,"handle":"","repo_id":1,"owner_id":1,"name":"test","needs":null,"runs_on":["debian"],"task_id":0,"status":"waiting"}]
$ forgejo-runner one-job
INFO[0000] No configuration file specified; using default settings.
INFO[2026-03-24T17:06:52+01:00] Starting job
INFO[2026-03-24T17:06:52+01:00] runner: forgejo-debug, with version: v12.7.2+10-ga53c8ada, with labels: [debian docker], ephemeral: false, declared successfully
INFO[2026-03-24T17:06:52+01:00] task 215 repo is andreas/test https://data.forgejo.org http://192.168.178.62:3000/
INFO[2026-03-24T17:06:57+01:00] Cleaning up network for job test, and network name is: WORKFLOW-c416f7c6d1733414bc9916c187741849
$ curl -u andreas --basic http://192.168.178.62:3000/api/v1/repos/andreas/test/actions/runners/jobs
null
```

The job 300 has no handle due to the Forgejo upgrade to v15. The last invocation of `forgejo-runner one-job` demonstrates that those tasks can still be executed.

PR for the extension of the runner protocol: https://code.forgejo.org/forgejo/actions-proto/pulls/18

PR that implements job filtering in Forgejo: https://codeberg.org/forgejo/forgejo/pulls/11676

<!--start release-notes-assistant-->
<!--URL:https://code.forgejo.org/forgejo/runner-->
- features
  - [PR](https://code.forgejo.org/forgejo/runner/pulls/1443): <!--number 1443 --><!--line 0 --><!--description ZmVhdDogZW5hYmxlIGBvbmUtam9iYCB0byByZXF1ZXN0IGEgcGFydGljdWxhciBqb2I=-->feat: enable `one-job` to request a particular job<!--description-->
<!--end release-notes-assistant-->

Reviewed-on: https://code.forgejo.org/forgejo/runner/pulls/1443
Reviewed-by: Mathieu Fenniak <mfenniak@noreply.code.forgejo.org>
Co-authored-by: Andreas Ahlenstorf <andreas@ahlenstorf.ch>
Co-committed-by: Andreas Ahlenstorf <andreas@ahlenstorf.ch>