fix: quit in daemon-mode when runner should be ephemeral (#1471)
Removes support for ephemeral runners from `forgejo-runner daemon`. If one Forgejo connection requires an ephemeral runner, `forgejo-runner daemon` now quits immediately with an error.

```
$ forgejo-runner -c config.yaml daemon
INFO[2026-04-02T15:56:58+02:00] Starting runner daemon
INFO[2026-04-02T15:56:58+02:00] runner: forgejo-debug, with version: v12.7.3+15-g4e6b3d17, with labels: [debian ubuntu-latest docker], ephemeral: false, declared successfully
INFO[2026-04-02T15:56:58+02:00] runner: ephemeral-5, with version: v12.7.3+15-g4e6b3d17, with labels: [debian ubuntu-latest docker], ephemeral: true, declared successfully
Error: connection "ephemeral" requires an ephemeral runner, which is not supported in daemon-mode
```

When ephemeral runner support was introduced in https://code.forgejo.org/forgejo/runner/pulls/1122, adding it to the daemon mode was already questionable because it is a misconfiguration. Ephemeral runners should at most run one job, which is not what the daemon mode does. To mitigate that problem, `capacity` was forcefully reduced to 1, and the daemon mode would quit after executing one job. As a result, `forgejo-runner daemon` would behave as `forgejo-runner one-job --wait`.

When support for multiple connections was added to the daemon mode in https://code.forgejo.org/forgejo/runner/pulls/1380, daemon mode would run at most one job _per connection_ instead of totally. That undermines the guarantees that ephemeral runners are supposed to provide, especially when run in host mode.

Instead of trying to patch things up and adding further complications, support for ephemeral runners is removed from `forgejo-runner daemon`. `forgejo-runner one-job` should be used instead.

<!--start release-notes-assistant-->
<!--URL:https://code.forgejo.org/forgejo/runner-->
- bug fixes
  - [PR](https://code.forgejo.org/forgejo/runner/pulls/1471): <!--number 1471 --><!--line 0 --><!--description Zml4OiBxdWl0IGluIGRhZW1vbi1tb2RlIHdoZW4gcnVubmVyIHNob3VsZCBiZSBlcGhlbWVyYWw=-->fix: quit in daemon-mode when runner should be ephemeral<!--description-->
<!--end release-notes-assistant-->

Reviewed-on: https://code.forgejo.org/forgejo/runner/pulls/1471
Reviewed-by: Mathieu Fenniak <mfenniak@noreply.code.forgejo.org>
Co-authored-by: Andreas Ahlenstorf <andreas@ahlenstorf.ch>
Co-committed-by: Andreas Ahlenstorf <andreas@ahlenstorf.ch>