fix: return error when `one-job` receives no task (#1477)
In Forgejo Runner 12.8, `forgejo-runner one-job` accidentally exited with 0 when no job was received. This change restores the old behaviour, but exits with 2 instead of 1. That makes it possible to distinguish "no job received" from all other errors.

Example:

```
> ./forgejo-runner -c config.yaml one-job
INFO[2026-04-07T13:14:04+02:00] Starting job
INFO[2026-04-07T13:14:04+02:00] runner: forgejo-debug, with version: v12.8.1, with labels: [debian ubuntu-latest docker], ephemeral: false, declared successfully
INFO[2026-04-07T13:14:04+02:00] single task poller launched
INFO[2026-04-07T13:14:04+02:00] single task poller is shutting down
Error: no task received
> echo $status
2
```

With 12.7.3:

```
> ./forgejo-runner -c config.yaml one-job
INFO[2026-04-07T13:15:07+02:00] Starting job
INFO[2026-04-07T13:15:07+02:00] runner: forgejo-debug, with version: v12.7.3, with labels: [debian ubuntu-latest docker], ephemeral: false, declared successfully
Error: could not fetch task
> echo $status
1
```

<!--start release-notes-assistant-->
<!--URL:https://code.forgejo.org/forgejo/runner-->
- bug fixes
  - [PR](https://code.forgejo.org/forgejo/runner/pulls/1477): <!--number 1477 --><!--line 0 --><!--description Zml4OiByZXR1cm4gZXJyb3Igd2hlbiBgb25lLWpvYmAgcmVjZWl2ZXMgbm8gdGFzaw==-->fix: return error when `one-job` receives no task<!--description-->
<!--end release-notes-assistant-->

Reviewed-on: https://code.forgejo.org/forgejo/runner/pulls/1477
Reviewed-by: Mathieu Fenniak <mfenniak@noreply.code.forgejo.org>
Co-authored-by: Andreas Ahlenstorf <andreas@ahlenstorf.ch>
Co-committed-by: Andreas Ahlenstorf <andreas@ahlenstorf.ch>